services:
  db:
    image: postgres:16
    container_name: lurexo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lurexo
      POSTGRES_PASSWORD: lurexo
      POSTGRES_DB: lurexo
    volumes:
      - lurexo_pgdata:/var/lib/postgresql/data
volumes:
  lurexo_pgdata:
